// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIBcrypt is an autogenerated mock type for the IBcrypt type
type MockIBcrypt struct {
	mock.Mock
}

type MockIBcrypt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBcrypt) EXPECT() *MockIBcrypt_Expecter {
	return &MockIBcrypt_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: password, hashed
func (_m *MockIBcrypt) Compare(password string, hashed string) bool {
	ret := _m.Called(password, hashed)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hashed)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIBcrypt_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockIBcrypt_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - password string
//   - hashed string
func (_e *MockIBcrypt_Expecter) Compare(password interface{}, hashed interface{}) *MockIBcrypt_Compare_Call {
	return &MockIBcrypt_Compare_Call{Call: _e.mock.On("Compare", password, hashed)}
}

func (_c *MockIBcrypt_Compare_Call) Run(run func(password string, hashed string)) *MockIBcrypt_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIBcrypt_Compare_Call) Return(_a0 bool) *MockIBcrypt_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIBcrypt_Compare_Call) RunAndReturn(run func(string, string) bool) *MockIBcrypt_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: plain
func (_m *MockIBcrypt) Hash(plain string) (string, error) {
	ret := _m.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plain)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plain)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIBcrypt_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockIBcrypt_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plain string
func (_e *MockIBcrypt_Expecter) Hash(plain interface{}) *MockIBcrypt_Hash_Call {
	return &MockIBcrypt_Hash_Call{Call: _e.mock.On("Hash", plain)}
}

func (_c *MockIBcrypt_Hash_Call) Run(run func(plain string)) *MockIBcrypt_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIBcrypt_Hash_Call) Return(_a0 string, _a1 error) *MockIBcrypt_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIBcrypt_Hash_Call) RunAndReturn(run func(string) (string, error)) *MockIBcrypt_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIBcrypt creates a new instance of MockIBcrypt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBcrypt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBcrypt {
	mock := &MockIBcrypt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
