// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockIUUID is an autogenerated mock type for the IUUID type
type MockIUUID struct {
	mock.Mock
}

type MockIUUID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUUID) EXPECT() *MockIUUID_Expecter {
	return &MockIUUID_Expecter{mock: &_m.Mock}
}

// NewV7 provides a mock function with no fields
func (_m *MockIUUID) NewV7() (uuid.UUID, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewV7")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUUID_NewV7_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewV7'
type MockIUUID_NewV7_Call struct {
	*mock.Call
}

// NewV7 is a helper method to define mock.On call
func (_e *MockIUUID_Expecter) NewV7() *MockIUUID_NewV7_Call {
	return &MockIUUID_NewV7_Call{Call: _e.mock.On("NewV7")}
}

func (_c *MockIUUID_NewV7_Call) Run(run func()) *MockIUUID_NewV7_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUUID_NewV7_Call) Return(_a0 uuid.UUID, _a1 error) *MockIUUID_NewV7_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUUID_NewV7_Call) RunAndReturn(run func() (uuid.UUID, error)) *MockIUUID_NewV7_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUUID creates a new instance of MockIUUID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUUID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUUID {
	mock := &MockIUUID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
