// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/nathakusuma/elevateu-backend/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIAuthRepository is an autogenerated mock type for the IAuthRepository type
type MockIAuthRepository struct {
	mock.Mock
}

type MockIAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthRepository) EXPECT() *MockIAuthRepository_Expecter {
	return &MockIAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateAuthSession provides a mock function with given fields: ctx, authSession
func (_m *MockIAuthRepository) CreateAuthSession(ctx context.Context, authSession *entity.AuthSession) error {
	ret := _m.Called(ctx, authSession)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuthSession) error); ok {
		r0 = rf(ctx, authSession)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_CreateAuthSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthSession'
type MockIAuthRepository_CreateAuthSession_Call struct {
	*mock.Call
}

// CreateAuthSession is a helper method to define mock.On call
//   - ctx context.Context
//   - authSession *entity.AuthSession
func (_e *MockIAuthRepository_Expecter) CreateAuthSession(ctx interface{}, authSession interface{}) *MockIAuthRepository_CreateAuthSession_Call {
	return &MockIAuthRepository_CreateAuthSession_Call{Call: _e.mock.On("CreateAuthSession", ctx, authSession)}
}

func (_c *MockIAuthRepository_CreateAuthSession_Call) Run(run func(ctx context.Context, authSession *entity.AuthSession)) *MockIAuthRepository_CreateAuthSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuthSession))
	})
	return _c
}

func (_c *MockIAuthRepository_CreateAuthSession_Call) Return(_a0 error) *MockIAuthRepository_CreateAuthSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_CreateAuthSession_Call) RunAndReturn(run func(context.Context, *entity.AuthSession) error) *MockIAuthRepository_CreateAuthSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthSession provides a mock function with given fields: ctx, userID
func (_m *MockIAuthRepository) DeleteAuthSession(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_DeleteAuthSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthSession'
type MockIAuthRepository_DeleteAuthSession_Call struct {
	*mock.Call
}

// DeleteAuthSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockIAuthRepository_Expecter) DeleteAuthSession(ctx interface{}, userID interface{}) *MockIAuthRepository_DeleteAuthSession_Call {
	return &MockIAuthRepository_DeleteAuthSession_Call{Call: _e.mock.On("DeleteAuthSession", ctx, userID)}
}

func (_c *MockIAuthRepository_DeleteAuthSession_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockIAuthRepository_DeleteAuthSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAuthRepository_DeleteAuthSession_Call) Return(_a0 error) *MockIAuthRepository_DeleteAuthSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_DeleteAuthSession_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIAuthRepository_DeleteAuthSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePasswordResetOTP provides a mock function with given fields: ctx, email
func (_m *MockIAuthRepository) DeletePasswordResetOTP(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeletePasswordResetOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_DeletePasswordResetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePasswordResetOTP'
type MockIAuthRepository_DeletePasswordResetOTP_Call struct {
	*mock.Call
}

// DeletePasswordResetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuthRepository_Expecter) DeletePasswordResetOTP(ctx interface{}, email interface{}) *MockIAuthRepository_DeletePasswordResetOTP_Call {
	return &MockIAuthRepository_DeletePasswordResetOTP_Call{Call: _e.mock.On("DeletePasswordResetOTP", ctx, email)}
}

func (_c *MockIAuthRepository_DeletePasswordResetOTP_Call) Run(run func(ctx context.Context, email string)) *MockIAuthRepository_DeletePasswordResetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_DeletePasswordResetOTP_Call) Return(_a0 error) *MockIAuthRepository_DeletePasswordResetOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_DeletePasswordResetOTP_Call) RunAndReturn(run func(context.Context, string) error) *MockIAuthRepository_DeletePasswordResetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRegisterOTP provides a mock function with given fields: ctx, email
func (_m *MockIAuthRepository) DeleteRegisterOTP(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRegisterOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_DeleteRegisterOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRegisterOTP'
type MockIAuthRepository_DeleteRegisterOTP_Call struct {
	*mock.Call
}

// DeleteRegisterOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuthRepository_Expecter) DeleteRegisterOTP(ctx interface{}, email interface{}) *MockIAuthRepository_DeleteRegisterOTP_Call {
	return &MockIAuthRepository_DeleteRegisterOTP_Call{Call: _e.mock.On("DeleteRegisterOTP", ctx, email)}
}

func (_c *MockIAuthRepository_DeleteRegisterOTP_Call) Run(run func(ctx context.Context, email string)) *MockIAuthRepository_DeleteRegisterOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_DeleteRegisterOTP_Call) Return(_a0 error) *MockIAuthRepository_DeleteRegisterOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_DeleteRegisterOTP_Call) RunAndReturn(run func(context.Context, string) error) *MockIAuthRepository_DeleteRegisterOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthSessionByToken provides a mock function with given fields: ctx, token
func (_m *MockIAuthRepository) GetAuthSessionByToken(ctx context.Context, token string) (*entity.AuthSession, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthSessionByToken")
	}

	var r0 *entity.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.AuthSession, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.AuthSession); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthRepository_GetAuthSessionByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthSessionByToken'
type MockIAuthRepository_GetAuthSessionByToken_Call struct {
	*mock.Call
}

// GetAuthSessionByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIAuthRepository_Expecter) GetAuthSessionByToken(ctx interface{}, token interface{}) *MockIAuthRepository_GetAuthSessionByToken_Call {
	return &MockIAuthRepository_GetAuthSessionByToken_Call{Call: _e.mock.On("GetAuthSessionByToken", ctx, token)}
}

func (_c *MockIAuthRepository_GetAuthSessionByToken_Call) Run(run func(ctx context.Context, token string)) *MockIAuthRepository_GetAuthSessionByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_GetAuthSessionByToken_Call) Return(_a0 *entity.AuthSession, _a1 error) *MockIAuthRepository_GetAuthSessionByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthRepository_GetAuthSessionByToken_Call) RunAndReturn(run func(context.Context, string) (*entity.AuthSession, error)) *MockIAuthRepository_GetAuthSessionByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordResetOTP provides a mock function with given fields: ctx, email
func (_m *MockIAuthRepository) GetPasswordResetOTP(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordResetOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthRepository_GetPasswordResetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordResetOTP'
type MockIAuthRepository_GetPasswordResetOTP_Call struct {
	*mock.Call
}

// GetPasswordResetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuthRepository_Expecter) GetPasswordResetOTP(ctx interface{}, email interface{}) *MockIAuthRepository_GetPasswordResetOTP_Call {
	return &MockIAuthRepository_GetPasswordResetOTP_Call{Call: _e.mock.On("GetPasswordResetOTP", ctx, email)}
}

func (_c *MockIAuthRepository_GetPasswordResetOTP_Call) Run(run func(ctx context.Context, email string)) *MockIAuthRepository_GetPasswordResetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_GetPasswordResetOTP_Call) Return(_a0 string, _a1 error) *MockIAuthRepository_GetPasswordResetOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthRepository_GetPasswordResetOTP_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockIAuthRepository_GetPasswordResetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegisterOTP provides a mock function with given fields: ctx, email
func (_m *MockIAuthRepository) GetRegisterOTP(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetRegisterOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthRepository_GetRegisterOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegisterOTP'
type MockIAuthRepository_GetRegisterOTP_Call struct {
	*mock.Call
}

// GetRegisterOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuthRepository_Expecter) GetRegisterOTP(ctx interface{}, email interface{}) *MockIAuthRepository_GetRegisterOTP_Call {
	return &MockIAuthRepository_GetRegisterOTP_Call{Call: _e.mock.On("GetRegisterOTP", ctx, email)}
}

func (_c *MockIAuthRepository_GetRegisterOTP_Call) Run(run func(ctx context.Context, email string)) *MockIAuthRepository_GetRegisterOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_GetRegisterOTP_Call) Return(_a0 string, _a1 error) *MockIAuthRepository_GetRegisterOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthRepository_GetRegisterOTP_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockIAuthRepository_GetRegisterOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SetPasswordResetOTP provides a mock function with given fields: ctx, email, otp
func (_m *MockIAuthRepository) SetPasswordResetOTP(ctx context.Context, email string, otp string) error {
	ret := _m.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for SetPasswordResetOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_SetPasswordResetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPasswordResetOTP'
type MockIAuthRepository_SetPasswordResetOTP_Call struct {
	*mock.Call
}

// SetPasswordResetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - otp string
func (_e *MockIAuthRepository_Expecter) SetPasswordResetOTP(ctx interface{}, email interface{}, otp interface{}) *MockIAuthRepository_SetPasswordResetOTP_Call {
	return &MockIAuthRepository_SetPasswordResetOTP_Call{Call: _e.mock.On("SetPasswordResetOTP", ctx, email, otp)}
}

func (_c *MockIAuthRepository_SetPasswordResetOTP_Call) Run(run func(ctx context.Context, email string, otp string)) *MockIAuthRepository_SetPasswordResetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_SetPasswordResetOTP_Call) Return(_a0 error) *MockIAuthRepository_SetPasswordResetOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_SetPasswordResetOTP_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIAuthRepository_SetPasswordResetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SetRegisterOTP provides a mock function with given fields: ctx, email, otp
func (_m *MockIAuthRepository) SetRegisterOTP(ctx context.Context, email string, otp string) error {
	ret := _m.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for SetRegisterOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_SetRegisterOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRegisterOTP'
type MockIAuthRepository_SetRegisterOTP_Call struct {
	*mock.Call
}

// SetRegisterOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - otp string
func (_e *MockIAuthRepository_Expecter) SetRegisterOTP(ctx interface{}, email interface{}, otp interface{}) *MockIAuthRepository_SetRegisterOTP_Call {
	return &MockIAuthRepository_SetRegisterOTP_Call{Call: _e.mock.On("SetRegisterOTP", ctx, email, otp)}
}

func (_c *MockIAuthRepository_SetRegisterOTP_Call) Run(run func(ctx context.Context, email string, otp string)) *MockIAuthRepository_SetRegisterOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_SetRegisterOTP_Call) Return(_a0 error) *MockIAuthRepository_SetRegisterOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_SetRegisterOTP_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIAuthRepository_SetRegisterOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAuthRepository creates a new instance of MockIAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthRepository {
	mock := &MockIAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
